azure/linux-virtual-machine/README.md
azure/linux-virtual-machine/main.tf
azure/linux-virtual-machine/variables.tf
azure/windows-virtual-machine/README.md
azure/windows-virtual-machine/main.tf
azure/windows-virtual-machine/variables.tf

Add license_type variable to Virtual Machine modules to support Bring Your Own License and Hybrid License models.

Azure VM - Add license_type variable to support byol/hybrid licensing

---

azure/linux-virtual-machine/README.md
azure/linux-virtual-machine/main.tf
azure/linux-virtual-machine/variables.tf
azure/windows-virtual-machine/README.md
azure/windows-virtual-machine/main.tf
azure/windows-virtual-machine/variables.tf

Add the "patch_assessment_mode" variable to VM resources to support this property.

Azure VM - Add patch_assessment_mode variable

---

azure/linux-functionapp/README.md
azure/linux-functionapp/locals.tf
azure/linux-functionapp/main.tf
azure/linux-functionapp/variables.tf

Add Sticky Settings to the Azure Functionapp module. These can be autogenerated when updating the app e.g. when setting up App Insights.

Azure Functionapp - Add Sticky Settings

---

azure/linux-webapp/README.md
azure/linux-webapp/locals.tf
azure/linux-webapp/main.tf
azure/linux-webapp/variables.tf

Add Sticky Settings to the Azure Webapp module. These can be autogenerated when updating the app e.g. when setting up App Insights.

Azure Webapp - Add Sticky Settings

---

azure/terraform-ops/README.md
azure/terraform-ops/data.tf
azure/terraform-ops/examples/basic/main.tf
azure/terraform-ops/main.tf
azure/terraform-ops/outputs.tf
azure/terraform-ops/variables.tf
azure/terraform-ops/versions.tf

Update to Terraform-Ops to modify the general structure of the created resources.

Terraform Ops - Structure Update

---

azure/linux-functionapp/README.md
azure/linux-functionapp/main.tf
azure/linux-functionapp/variables.tf

Added a variable to allow switching of

added shared access key setting

---

azuredevops/pipelines/README.md
azuredevops/pipelines/variables.tf

Please provide a summary of your changes and the reason the changes are being made.

updated refs/heads/main

---

azure/linux-virtual-machine/README.md
azure/windows-virtual-machine/README.md

Updated Readme to include instructions to accept terms

updated vm readme to include accepting images

---

azure/linux-functionapp/README.md
azure/linux-functionapp/examples/basic/main.tf
azure/linux-functionapp/locals.tf
azure/linux-functionapp/main.tf
azure/linux-functionapp/outputs.tf
azure/linux-functionapp/variables.tf
azure/linux-webapp/README.md
azure/linux-webapp/examples/basic/main.tf
azure/linux-webapp/locals.tf
azure/linux-webapp/main.tf
azure/linux-webapp/outputs.tf
azure/linux-webapp/variables.tf

General improvements to the modules. These improvements include:
- Inclusion of `slots` variable to enable creation of slots based on the app, with corresponding output.
- Inclusion of `create_application_insights` variable to enable creation of app insights
- Create App Insights as part of the module.
- default_documents set as a dedicated var to prevent issues when customizing site_config, as this caused some type conflicts
- default sticky app settings for settings that might get set via other features e.g. implementing app insights
- cleanup to ip restrictions
- hardcode tls requirements to 1.2
- add lifecycle rules to prevent changes triggered by more transient properties e.g. docker image tag, hidden tags managed by azure
Additionally the changes below have been made for now for …

March - App Service and Function App Improvements

---

azure/linux-virtual-machine/README.md
azure/linux-virtual-machine/examples/advanced/main.tf
azure/linux-virtual-machine/main.tf
azure/linux-virtual-machine/variables.tf
azure/windows-virtual-machine/README.md
azure/windows-virtual-machine/examples/advanced/main.tf
azure/windows-virtual-machine/main.tf
azure/windows-virtual-machine/variables.tf

Add the Autoshutdown feature to Azure virtual machines.

Add Autoshutdown to Azure VM

---

.github/workflows/tf.test.azure.windows-webapp.yml
azure/windows-webapp/windows-webapp/.gitignore
azure/windows-webapp/windows-webapp/.terraform-docs.yml
azure/windows-webapp/windows-webapp/.tflint.hcl
azure/windows-webapp/windows-webapp/README.md
azure/windows-webapp/windows-webapp/examples/advanced/.terraform-docs.yml
azure/windows-webapp/windows-webapp/examples/advanced/README.md
azure/windows-webapp/windows-webapp/examples/advanced/main.tf
azure/windows-webapp/windows-webapp/examples/basic/.terraform-docs.yml
azure/windows-webapp/windows-webapp/examples/basic/README.md
azure/windows-webapp/windows-webapp/examples/basic/main.tf
azure/windows-webapp/windows-webapp/examples/logging/.terraform-docs.yml
azure/windows-webapp/windows-webapp/examples/logging/README.md
azure/windows-webapp/windows-webapp/examples/logging/main.tf
azure/windows-webapp/windows-webapp/examples/privatelink/.terraform-docs.yml
azure/windows-webapp/windows-webapp/examples/privatelink/README.md
azure/windows-webapp/windows-webapp/examples/privatelink/main.tf
azure/windows-webapp/windows-webapp/locals.tf
azure/windows-webapp/windows-webapp/main.tf
azure/windows-webapp/windows-webapp/outputs.tf
azure/windows-webapp/windows-webapp/variables.tf
azure/windows-webapp/windows-webapp/versions.tf

This PR introduces the Windows Webapp module to the repository.

Add Azure Windows Webapp Module

---

.gitmodules

updated submodule url

---

azure/network-security-group/examples/advanced/main.tf

Fixed nsg name in advanced example
Fixed #34 
Please provide a summary of your changes and the reason the changes are being made.

Fixed nsg name in advanced example

---

azuredevops/project/README.md
azuredevops/project/examples/advanced/README.md
azuredevops/project/examples/advanced/main.tf
azuredevops/project/examples/basic/README.md
azuredevops/project/examples/basic/main.tf
azuredevops/project/locals.tf
azuredevops/project/main.tf
azuredevops/project/outputs.tf
azuredevops/project/variables.tf
azuredevops/project/versions.tf

Updated input types from `list(object({})` to `object({})` in sections and updated the relevant examples. This should make config easier to read and more obvious, however is a breaking change.
Environment Checks have also been added allowing for branch checking and approval gates.
- [*] New feature (non-breaking change which adds functionality)
- [*] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [*] My code follows the style guidelines of this project
- [*] I have performed a self-review of my code
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] I have made corresponding changes to the documentation
- [*] My changes generate no new warnings e.g. code analysis …

Update ADO Project Input Types and add Environment Checks

---

azure/linux-webapp/README.md
azure/linux-webapp/examples/advanced/README.md
azure/linux-webapp/examples/advanced/main.tf
azure/linux-webapp/examples/basic/main.tf
azure/linux-webapp/examples/logging/.terraform-docs.yml
azure/linux-webapp/examples/logging/README.md
azure/linux-webapp/examples/logging/main.tf
azure/linux-webapp/examples/privatelink/main.tf
azure/linux-webapp/locals.tf
azure/linux-webapp/main.tf
azure/linux-webapp/outputs.tf
azure/linux-webapp/variables.tf
azure/linux-webapp/versions.tf

Update the Linux Webapp which involves the following changes:
- Removal of inbuilt logs and promotion of usage of `azurerm_monitor_diagnostic_setting` for logs. A new example has been added to demonstrate this.
- This means that we've removed precreated storage etc., but diagnostics will prove for easier log shipping.
- "log_config" variable is now just "logs"
- Blob config for logs has been ignored on the resource
- Default sticky setting added for Microsoft authentication, ignore rule created for `auth_settings_v2` on app to avoid changes.
- Autocreated RG removed, mandating an RG be provided in a variable
- "go_version" added to application_stack
- Slots are now a feature, which should 100% mimic the origin slot

Update Linux Webapp - Apr '23

---

azure/application-gateway/advanced/examples/advanced/main.tf
azure/application-gateway/advanced/keyvault.tf
azure/application-gateway/advanced/main.tf
azure/application-gateway/advanced/outputs.tf
azure/application-gateway/advanced/variables.tf

added IP address outputs

---

_template/versions.tf

We should always ensure that we're using the latest version of Terraform for modules going forwards.
Although the code might work on previous versions of Terraform, these are untested and we should bump all versions to the version that we have access to test (which is generally the latest).

Updated The Example Module

---

azure/windows-webapp/main.tf
azure/windows-webapp/variables.tf

Added ability to enable public access on Windows Web App

added ability to set public access enabled

---

azure/windows-webapp/README.md
azure/windows-webapp/examples/advanced/main.tf
azure/windows-webapp/main.tf
azure/windows-webapp/variables.tf

More than one Virtual Application can be defined in App Service. This change adds support for this by creating a set of virtual applications rather than a single one

Added Ability To Have Multiple Virtual Applications

---

azure/application-gateway/advanced/keyvault.tf

Update to keyvault

---

azure/network-security-group/README.md
azure/network-security-group/examples/subnets/.terraform-docs.yml
azure/network-security-group/examples/subnets/README.md
azure/network-security-group/examples/subnets/main.tf
azure/network-security-group/main.tf
azure/network-security-group/outputs.tf
azure/network-security-group/variables.tf
azure/network-security-group/versions.tf

Adding subnet association + example

Network Security Group Improvements

---

azure/route-table/.gitignore
azure/route-table/.pre-commit-config.yaml
azure/route-table/.terraform-docs.yml
azure/route-table/.tflint.hcl
azure/route-table/LICENSE
azure/route-table/README.md
azure/route-table/examples/basic/.terraform-docs.yml
azure/route-table/examples/basic/README.md
azure/route-table/examples/basic/main.tf
azure/route-table/main.tf
azure/route-table/outputs.tf
azure/route-table/variables.tf
azure/route-table/versions.tf

Creating a route table module that can be associated with multiple subnets.  
The use case is for spokes that require multiple subnets with seperate route tables.

Adding Route Table Module

---

azure/network-security-group/README.md
azure/network-security-group/examples/advanced/README.md
azure/network-security-group/examples/advanced/main.tf
azure/network-security-group/main.tf
azure/network-security-group/outputs.tf
azure/spoke/README.md
azure/spoke/examples/advanced/README.md
azure/spoke/examples/advanced/main.tf
azure/spoke/main.tf
azure/spoke/outputs.tf
azure/spoke/variables.tf
azure/spoke/versions.tf

Various fixes to spoke module
I'm looking to create a peering module in the future that compatible with multiple scriptions.  It's too complicated to incorportate in this module.
Fixes to Outputs
Added a depends_on to the flow logs in the nsg module because terraform was trying to destroy the flow_logs after it had destroyed the nsg, resulting in an error.
- [*] Bug fix (non-breaking change which fixes an issue)
- [*] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [*] This change requires a documentation update
- [*] My code follows the style guidelines of this project
- [*] I have performed a self-review of my code
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] I …

Small fixes to spoke and nsg module.

---

azure/application-gateway/advanced/README.md

Please provide a summary of your changes and the reason the changes are being made.

changes to docs

---

azure/app-service/webapp/README.md
azure/app-service/webapp/key_vault.tf
azure/app-service/webapp/locals.tf
azure/app-service/webapp/outputs.tf
azure/application-gateway/advanced/keyvault.tf

Quick fix to App Service & App Gateway to allow Import permissions on Keyvault
Also added some outputs to App Service to allow UMID to be used with Keyvault for secrets

Fix App Service - Outputs & KV Permissions

---

azure/linux-functionapp/README.md
azure/linux-functionapp/main.tf
azure/linux-functionapp/variables.tf

Please provide a summary of your changes and the reason the changes are being made.

add public access support

---

azure/app-service/webapp/linux.tf
azure/app-service/webapp/windows.tf

Syntax error in terraform code when using set within dynamic. 

Fixes to web app restriction

---

azure/route-table/variables.tf

Removing address_prefix IPv4 validation on the route variable - tags are also possible here

Route Table - Removing route validation
